---
- name: Install, upgrade, or downgrade Apache2 to a specific version based on distribution
  hosts: all
  become: yes
  vars:
    apache2_version_debian: "2.4.29-1ubuntu4.14"
    apache2_version_redhat: "2.4.6-90.el7.centos"

  tasks:
    - name: Update apt cache (Debian/Ubuntu)
      apt:
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Update yum cache (RedHat/CentOS)
      yum:
        update_cache: yes
      when: ansible_facts['os_family'] == "RedHat"

    - name: Install, upgrade, or downgrade Apache2 on Debian/Ubuntu
      apt:
        name: "apache2={{ apache2_version_debian }}"
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Install, upgrade, or downgrade Apache2 on RedHat/CentOS
      yum:
        name: "httpd-{{ apache2_version_redhat }}"
        state: present
      when: ansible_facts['os_family'] == "RedHat"

    - name: Ensure Apache2 is running on Debian/Ubuntu
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Ensure Apache2 is running on RedHat/CentOS
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_facts['os_family'] == "RedHat"
