---
- name: Check and Install Apache2 on Debian/Ubuntu
  hosts: all
  become: yes
  vars:
    apache2_version_debian: "2.4.52-1ubuntu4.6"

  tasks:
    - name: Check available Apache2 versions on Debian/Ubuntu
      shell: "apt-cache madison apache2"
      register: apache2_versions
      when: ansible_facts['os_family'] == "Debian"

    - name: Display available Apache2 versions
      debug:
        var: apache2_versions.stdout_lines
      when: ansible_facts['os_family'] == "Debian"

    - name: Update apt cache (Debian/Ubuntu)
      apt:
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Install the specific version of Apache2
      apt:
        name: "apache2={{ apache2_version_debian }}"
        state: present
      when: 
        - ansible_facts['os_family'] == "Debian"
        - "'apache2={{ apache2_version_debian }}' in apache2_versions.stdout"

    - name: Ensure Apache2 is running
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_facts['os_family'] == "Debian"
