---
- name: Install and Configure Apache2 on Debian/Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: "Step 1: Update apt cache"
      apt:
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"
      register: update_cache_result

    - name: "Notify: apt cache updated"
      debug:
        msg: "apt cache update completed successfully."
      when: update_cache_result.changed

    - name: "Step 2: Install Apache2 package"
      apt:
        name: apache2
        state: present
        force: yes
        install_recommends: yes
      when: ansible_facts['os_family'] == "Debian"
      register: install_apache_result

    - name: "Notify: Apache2 installation completed"
      debug:
        msg: "Apache2 package installed successfully."
      when: install_apache_result.changed

    - name: "Step 3: Ensure Apache2 is active and enabled"
      systemd:
        name: apache2
        state: started
        enabled: yes
      when: ansible_facts['os_family'] == "Debian"
      register: apache_service_result

    - name: "Notify: Apache2 service status"
      debug:
        msg: >
          Apache2 service status:
          Active: {{ apache_service_result.status.active }}
          Enabled: {{ apache_service_result.status.enabled }}
      when: apache_service_result.changed

    - name: "Step 4: Check Apache2 version"
      shell: "apache2 -v | grep 'Server version'"
      when: ansible_facts['os_family'] == "Debian"
      register: apache_version

    - name: "Notify: Apache2 version"
      debug:
        msg: "Apache2 version installed: {{ apache_version.stdout }}"

    - name: "Completion: Apache2 installation and configuration completed"
      debug:
        msg: >
          Apache2 has been successfully installed, configured, and verified on all target hosts.
          Version: {{ apache_version.stdout.strip() }}
          Active: {{ apache_service_result.status.active }}
          Enabled: {{ apache_service_result.status.enabled }}
