---
- name: Check available Apache2 versions on target hosts
  hosts: all
  become: yes
  tasks:
    - name: Check available Apache2 versions on Debian/Ubuntu
      shell: "apt-cache madison apache2"
      register: apache2_versions
      when: ansible_facts['os_family'] == "Debian"

    - name: Display available Apache2 versions
      debug:
        var: apache2_versions.stdout_lines
      when: ansible_facts['os_family'] == "Debian"
