---
- name: Install Apache2 on Debian/Ubuntu
  hosts: all
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Install Apache2 package
      apt:
        name: apache2
        state: present
        force: yes
        install_recommends: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Ensure Apache2 is running
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_facts['os_family'] == "Debian"
