---
- name: Check reboot and kernel version across different distros
  hosts: all
  gather_facts: yes  # This is crucial to gather system information

  tasks:
    - name: Check if reboot is required (Ubuntu/Debian)
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file
      when: ansible_os_family == "Debian"

    - name: Display reboot required for Ubuntu/Debian
      debug:
        msg: "Reboot is required on Ubuntu/Debian."
      when: reboot_required_file.stat.exists

    - name: Check if reboot is required (RedHat/CentOS)
      shell: needs-restarting -r | grep 'reboot is required'
      register: reboot_required_command
      ignore_errors: true
      when: ansible_os_family == "RedHat"

    - name: Display reboot required for RedHat/CentOS
      debug:
        msg: "Reboot is required on RedHat/CentOS."
      when: reboot_required_command.rc == 0

    - name: Display current kernel version
      debug:
        msg: "Current kernel version is {{ ansible_kernel }}"
    
    - name: Skip message for unsupported distributions
      debug:
        msg: "This distribution is not supported for specific reboot checks."
      when: ansible_os_family not in ["Debian", "RedHat"]
