---
- name: Dynamic reboot and kernel checks for Ubuntu
  hosts: all
  gather_facts: yes

  tasks:
    - name: Check if reboot is required (Ubuntu)
      stat:
        path: /var/run/reboot-required
      register: reboot_required_ubuntu
      when: ansible_distribution == "Ubuntu"

    - name: Display reboot required message for Ubuntu
      debug:
        msg: "Reboot is required on Ubuntu."
      when: reboot_required_ubuntu.stat.exists and ansible_distribution == "Ubuntu"

    - name: Display no reboot required message for Ubuntu
      debug:
        msg: "No reboot is required on Ubuntu."
      when: not reboot_required_ubuntu.stat.exists and ansible_distribution == "Ubuntu"

    - name: Check for kernel updates (Ubuntu)
      apt:
        update_cache: yes
        cache_valid_time: 3600
      register: apt_update
      when: ansible_distribution == "Ubuntu"

    - name: Search for new kernel packages
      shell: apt list --upgradable | grep linux-image
      register: kernel_upgrade
      when: ansible_distribution == "Ubuntu" and apt_update.changed

    - name: Display current kernel version if an upgrade is available
      debug:
        msg: "Current kernel version {{ ansible_kernel }} is upgradable. Upgrade available: {{ kernel_upgrade.stdout }}"
      when: kernel_upgrade.stdout != "" and ansible_distribution == "Ubuntu"
