---
- name: Dynamic reboot and kernel version checks for multiple distributions
  hosts: all
  gather_facts: yes

  tasks:
    - name: Check if reboot is required (Ubuntu)
      stat:
        path: /var/run/reboot-required
      register: reboot_required_ubuntu
      when: ansible_distribution == "Ubuntu"

    - name: Display reboot required message for Ubuntu
      debug:
        msg: "Reboot is required on Ubuntu."
      when: reboot_required_ubuntu.stat.exists and ansible_distribution == "Ubuntu"

    - name: Check if reboot is required (CentOS)
      shell: needs-restarting -r | grep 'reboot is required'
      register: reboot_required_centos
      ignore_errors: true
      when: ansible_distribution == "CentOS"

    - name: Display reboot required message for CentOS
      debug:
        msg: "Reboot is required on CentOS."
      when: reboot_required_centos.rc == 0 and ansible_distribution == "CentOS"

    - name: Display current kernel version
      debug:
        msg: "Current kernel version on {{ inventory_hostname }} is {{ ansible_kernel }}"
