---
- name: Install Apache HTTPD from Source on Ubuntu
  hosts: all
  become: true
  vars:
    apache_version: "2.4.63"
    apr_version: "1.7.4"
    apr_util_version: "1.6.3"
    apache_prefix: "/usr/local/apache2"
    src_dir: "/usr/local/src"
    apache_download_url: "https://downloads.apache.org/httpd/httpd-{{ apache_version }}.tar.gz"
    apr_download_url: "https://downloads.apache.org/apr/apr-{{ apr_version }}.tar.gz"
    apr_util_download_url: "https://downloads.apache.org/apr/apr-util-{{ apr_util_version }}.tar.gz"

  tasks:
    - name: Install Required Dependencies
      apt:
        name:
          - build-essential
          - libpcre3
          - libpcre3-dev
          - libssl-dev
          - zlib1g-dev
          - wget
          - tar
        state: present
        update_cache: yes

    - name: Download Apache HTTPD Source
      get_url:
        url: "{{ apache_download_url }}"
        dest: "{{ src_dir }}/httpd-{{ apache_version }}.tar.gz"

    - name: Extract Apache HTTPD Source
      ansible.builtin.unarchive:
        src: "{{ src_dir }}/httpd-{{ apache_version }}.tar.gz"
        dest: "{{ src_dir }}/"
        remote_src: yes

    - name: Download APR Source
      get_url:
        url: "{{ apr_download_url }}"
        dest: "{{ src_dir }}/apr-{{ apr_version }}.tar.gz"

    - name: Extract APR Source
      ansible.builtin.unarchive:
        src: "{{ src_dir }}/apr-{{ apr_version }}.tar.gz"
        dest: "{{ src_dir }}/"
        remote_src: yes

    - name: Download APR-Util Source
      get_url:
        url: "{{ apr_util_download_url }}"
        dest: "{{ src_dir }}/apr-util-{{ apr_util_version }}.tar.gz"

    - name: Extract APR-Util Source
      ansible.builtin.unarchive:
        src: "{{ src_dir }}/apr-util-{{ apr_util_version }}.tar.gz"
        dest: "{{ src_dir }}/"
        remote_src: yes

    - name: Build and Install APR
      shell: |
        ./configure --prefix=/usr/local/apr
        make -j$(nproc)
        make install
      args:
        chdir: "{{ src_dir }}/apr-{{ apr_version }}"
        creates: "/usr/local/apr/bin/apr-1-config"

    - name: Build and Install APR-Util
      shell: |
        ./configure --prefix=/usr/local/apr --with-apr=/usr/local/apr
        make -j$(nproc)
        make install
      args:
        chdir: "{{ src_dir }}/apr-util-{{ apr_util_version }}"
        creates: "/usr/local/apr/bin/apu-1-config"

    - name: Configure Apache Source Code
      command:
        cmd: "./configure --prefix={{ apache_prefix }} --enable-ssl --enable-so --enable-mods-shared=all --with-mpm=event --with-apr=/usr/local/apr"
        chdir: "{{ src_dir }}/httpd-{{ apache_version }}"
        creates: "{{ src_dir }}/httpd-{{ apache_version }}/Makefile"

    - name: Compile Apache HTTPD
      command:
        cmd: "make -j{{ ansible_processor_vcpus }}"
        chdir: "{{ src_dir }}/httpd-{{ apache_version }}"
      async: 300
      poll: 10

    - name: Install Apache HTTPD
      command:
        cmd: "make install"
        chdir: "{{ src_dir }}/httpd-{{ apache_version }}"

    - name: Create Systemd Service for Apache
      copy:
        dest: /etc/systemd/system/apache2.service
        content: |
          [Unit]
          Description=Apache HTTPD
          After=network.target

          [Service]
          ExecStart={{ apache_prefix }}/bin/httpd -DFOREGROUND
          ExecReload={{ apache_prefix }}/bin/apachectl graceful
          ExecStop={{ apache_prefix }}/bin/apachectl stop
          Restart=always
          User=root
          Group=root

          [Install]
          WantedBy=multi-user.target

    - name: Reload Systemd Daemon
      systemd:
        daemon_reload: yes

    - name: Enable and Start Apache HTTPD
      systemd:
        name: apache2
        state: started
        enabled: yes

    - name: Open Firewall Ports for Apache (80 and 443)
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - 80
        - 443

    - name: Verify Apache Version
      command:
        cmd: "{{ apache_prefix }}/bin/httpd -v"
      register: apache_version_output
      changed_when: false

    - name: Print Apache Version
      debug:
        msg: "{{ apache_version_output.stdout }}"
