---
- name: Basic Apache2 Installation and Setup
  hosts: all
  become: yes
  tasks:
    - name: Ensure Apache2 is installed
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Ensure Apache2 is running and enabled on boot
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Allow HTTP and HTTPS ports through the firewall
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      with_items:
        - 80
        - 443

    - name: Ensure Apache environment variables are defined
      copy:
        dest: /etc/apache2/envvars
        content: |
          export APACHE_RUN_USER=www-data
          export APACHE_RUN_GROUP=www-data
          export APACHE_LOG_DIR=/var/log/apache2
          export APACHE_PID_FILE=/var/run/apache2/apache2.pid
          export APACHE_RUN_DIR=/var/run/apache2
          export APACHE_LOCK_DIR=/var/lock/apache2

    - 
