---
- name: Install Apache HTTPD from Source (Debian/Ubuntu Style)
  hosts: all
  become: true
  vars:
    apache_version: "2.4.58"
    apr_version: "1.7.2"
    apr_util_version: "1.6.3"
    pcre_version: "8.45"
    apache_prefix: "/etc/apache2"
    document_root: "/var/www/html"
    log_dir: "/var/log/apache2"
    
  tasks:
    - name: Install Required Dependencies
      apt:
        name:
          - build-essential
          - libpcre3
          - libpcre3-dev
          - libssl-dev
          - zlib1g-dev
          - wget
          - tar
        state: present
        update_cache: yes

    - name: Ensure Required Directories Exist
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /usr/local/src
        - "{{ document_root }}"
        - "{{ log_dir }}"

    - name: Download and Extract Apache HTTPD, APR, APR-Util
      get_url:
        url: "https://downloads.apache.org/httpd/httpd-{{ apache_version }}.tar.gz"
        dest: "/usr/local/src/httpd-{{ apache_version }}.tar.gz"

    - name: Configure Apache with Debian Paths
      command:
        cmd: >
          ./configure --prefix={{ apache_prefix }}
          --enable-ssl --enable-so
          --enable-mods-shared=all
          --with-mpm=event
          --with-included-apr
          --sysconfdir=/etc/apache2
          --localstatedir=/var
          --logfiledir={{ log_dir }}
          --datadir={{ document_root }}
        chdir: "/usr/local/src/httpd-{{ apache_version }}"

    - name: Compile and Install Apache
      command:
        cmd: "make && make install"
        chdir: "/usr/local/src/httpd-{{ apache_version }}"

    - name: Create Systemd Service for Apache
      copy:
        dest: /etc/systemd/system/apache2.service
        content: |
          [Unit]
          Description=Apache HTTPD
          After=network.target

          [Service]
          ExecStart={{ apache_prefix }}/bin/httpd -DFOREGROUND
          ExecReload={{ apache_prefix }}/bin/apachectl graceful
          ExecStop={{ apache_prefix }}/bin/apachectl stop
          Restart=always
          User=root
          Group=root

          [Install]
          WantedBy=multi-user.target

    - name: Enable and Start Apache HTTPD
      systemd:
        name: apache2
        state: started
        enabled: yes

    - name: Open Firewall Ports for Apache (80 and 443)
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - 80
        - 443

    - name: Verify Apache Version
      command:
        cmd: "{{ apache_prefix }}/bin/httpd -v"
      register: apache_version_output
      changed_when: false

    - name: Print Apache Version
      debug:
        msg: "{{ apache_version_output.stdout }}"
