- name: Install Apache HTTPD from Source
  hosts: all
  become: yes
  vars:
    apache_version: "2.4.63"
    apr_version: "1.7.5"
    apr_util_version: "1.6.3"
    apache_url: "https://downloads.apache.org/httpd/httpd-{{ apache_version }}.tar.gz"
    apr_url: "https://downloads.apache.org/apr/apr-{{ apr_version }}.tar.gz"
    apr_util_url: "https://downloads.apache.org/apr/apr-util-{{ apr_util_version }}.tar.gz"
    install_prefix: "/usr/local/apache2"

  tasks:
    - name: Install required dependencies
      apt:
        name:
          - build-essential
          - libpcre3
          - libpcre3-dev
          - libssl-dev
          - zlib1g-dev
          - perl
          - wget
          - tar
          - make
          - autoconf
          - libtool
          - pkg-config
        state: present
        update_cache: yes

    - name: Download Apache HTTPD source
      get_url:
        url: "{{ apache_url }}"
        dest: "/usr/src/httpd-{{ apache_version }}.tar.gz"

    - name: Extract Apache HTTPD source
      ansible.builtin.unarchive:
        src: "/usr/src/httpd-{{ apache_version }}.tar.gz"
        dest: "/usr/src/"
        remote_src: yes

    - name: Download APR and APR-Util
      get_url:
        url: "{{ item.url }}"
        dest: "/usr/src/{{ item.name }}.tar.gz"
      loop:
        - { url: "{{ apr_url }}", name: "apr" }
        - { url: "{{ apr_util_url }}", name: "apr-util" }

    - name: Extract APR and APR-Util
      ansible.builtin.unarchive:
        src: "/usr/src/{{ item }}.tar.gz"
        dest: "/usr/src/httpd-{{ apache_version }}/srclib/"
        remote_src: yes
      loop:
        - apr
        - apr-util

    - name: Rename APR directories
      command:
        cmd: mv /usr/src/httpd-{{ apache_version }}/srclib/{{ item }}-* /usr/src/httpd-{{ apache_version }}/srclib/{{ item }}
      loop:
        - apr
        - apr-util

    - name: Configure Apache HTTPD
      command:
        cmd: "./configure --prefix={{ install_prefix }} --enable-so --enable-ssl --enable-rewrite --with-included-apr"
        chdir: "/usr/src/httpd-{{ apache_version }}"

    - name: Compile Apache HTTPD
      command:
        cmd: "make -j$(nproc)"
        chdir: "/usr/src/httpd-{{ apache_version }}"

    - name: Install Apache HTTPD
      command:
        cmd: "make install"
        chdir: "/usr/src/httpd-{{ apache_version }}"

    - name: Create systemd service for Apache
      copy:
        dest: "/etc/systemd/system/apache2.service"
        content: |
          [Unit]
          Description=Apache HTTP Server
          After=network.target

          [Service]
          Type=forking
          ExecStart={{ install_prefix }}/bin/apachectl -k start
          ExecStop={{ install_prefix }}/bin/apachectl -k stop
          ExecReload={{ install_prefix }}/bin/apachectl -k graceful
          PIDFile={{ install_prefix }}/logs/httpd.pid
          PrivateTmp=true

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Enable and start Apache service
      systemd:
        name: apache2
        enabled: yes
        state: started
