---
- name: Troubleshoot fetching the latest available Ubuntu kernel version
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Update the package list
      ansible.builtin.apt:
        update_cache: yes

    - name: Fetch raw kernel version information
      shell: apt-cache madison linux-image-generic
      register: raw_kernel_info
      ignore_errors: yes

    - name: Display raw kernel version information
      debug:
        msg: "Raw kernel version info: {{ raw_kernel_info.stdout }}"

    - name: Display any errors from the kernel version fetch
      debug:
        msg: "Errors: {{ raw_kernel_info.stderr }}"
      when: raw_kernel_info.stderr is defined
