---
- name: Test capturing command output
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Run a simple echo command
      command: echo "Hello, World!"
      register: echo_output

    - name: Display the output of the echo command
      debug:
        var: echo_output
