---
- name: Debug kernel version retrieval
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Update the package list
      ansible.builtin.apt:
        update_cache: yes

    - name: Run apt-cache madison for linux-image-generic
      command: apt-cache madison linux-image-generic
      register: raw_kernel_info
      ignore_errors: yes

    - name: Display raw kernel version information
      debug:
        msg: "Raw kernel version info: {{ raw_kernel_info.stdout }}"
      when: raw_kernel_info.stdout is defined

    - name: Fail if raw kernel info is not found
      ansible.builtin.fail:
        msg: "Failed to retrieve kernel version information."
      when: raw_kernel_info.stdout is undefined or raw_kernel_info.stdout == ""

    - name: Extract the latest available kernel version
      command: "echo '{{ raw_kernel_info.stdout }}' | awk '{print $3}' | sort -V | tail -n 1"
      register: latest_kernel_version
      ignore_errors: yes

    - name: Display the extracted latest kernel version
      debug:
        msg: "Latest available kernel version: {{ latest_kernel_version.stdout }}"

    - name: Fail if latest kernel version is not found
      ansible.builtin.fail:
        msg: "Failed to determine the latest available kernel version after extraction."
      when: latest_kernel_version.stdout is undefined or latest_kernel_version.stdout == ""
