---
- name: Ensure the system is running the latest Ubuntu kernel
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Update the package list
      ansible.builtin.apt:
        update_cache: yes

    - name: Check the currently running kernel version
      ansible.builtin.command: uname -r
      register: current_kernel

    - name: Find the latest available kernel version
      ansible.builtin.shell: |
        apt-cache policy linux-generic | grep -m 1 Candidate | awk '{print $2}'
      register: latest_kernel_version

    - name: Debug the current and latest kernel versions
      ansible.builtin.debug:
        msg: "Current kernel: {{ current_kernel.stdout }}, Latest available kernel: {{ latest_kernel_version.stdout }}"

    - name: Compare current kernel with the latest available version
      ansible.builtin.shell: |
        dpkg -l | grep linux-image | grep {{ current_kernel.stdout }} | grep -q {{ latest_kernel_version.stdout }}
      register: is_latest_kernel_installed
      failed_when: false
      changed_when: false

    - name: Install the latest available kernel if it's not installed
      ansible.builtin.apt:
        name: linux-generic
        state: latest
      when: is_latest_kernel_installed.rc != 0
      register: kernel_update

    - name: Check if a reboot is required
      ansible.builtin.shell: |
        if [ -f /var/run/reboot-required ]; then echo "reboot_required"; fi
      register: reboot_required
      changed_when: reboot_required.stdout != ""
      check_mode: no

    - name: Debug reboot requirement
      ansible.builtin.debug:
        msg: "Reboot is required."
      when: reboot_required.stdout == "reboot_required"

    - name: Reboot the server if required
      ansible.builtin.reboot:
      when: reboot_required.stdout == "reboot_required"

    - name: Verify the running kernel after reboot
      ansible.builtin.command: uname -r
      register: running_kernel

    - name: Display the running kernel
      ansible.builtin.debug:
        msg: "The system is now running kernel version {{ running_kernel.stdout }}."
