---
- name: Simple command test
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Run a simple echo command
      command: echo "Hello, World!"
      register: echo_output

    - name: Display the output of the echo command
      debug:
        msg: "Echo command output: {{ echo_output.stdout }}"

    - name: Run apt-cache madison for linux-image-generic
      command: apt-cache madison linux-image-generic
      register: raw_kernel_info
      ignore_errors: yes

    - name: Display raw kernel version information
      debug:
        msg: "Raw kernel version info: {{ raw_kernel_info.stdout }}"
      when: raw_kernel_info.stdout is defined

    - name: Fail if raw kernel info is not found
      ansible.builtin.fail:
        msg: "Failed to retrieve kernel version information."
      when: raw_kernel_info.stdout is undefined or raw_kernel_info.stdout == ""
