---
- name: Ensure the system is running the latest Ubuntu kernel
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Update the package list
      ansible.builtin.apt:
        update_cache: yes

    - name: Install the latest available kernel
      ansible.builtin.apt:
        name: linux-generic
        state: latest
      register: kernel_update

    - name: Check if a reboot is required
      ansible.builtin.shell: |
        if [ -f /var/run/reboot-required ]; then echo "reboot_required"; fi
      register: reboot_required
      changed_when: reboot_required.stdout != ""
      check_mode: no

    - name: Reboot the server if required
      ansible.builtin.reboot:
      when: reboot_required.stdout == "reboot_required"

    - name: Verify the running kernel after reboot
      ansible.builtin.command: uname -r
      register: running_kernel

    - name: Debug running kernel version
      ansible.builtin.debug:
        msg: "The system is now running kernel version {{ running_kernel.stdout }}."
      when: running_kernel.stdout is defined

    - name: Check if the latest kernel was installed
      ansible.builtin.shell: |
        apt-cache policy linux-generic | grep Installed | awk '{print $2}'
      register: installed_kernel_version

    - name: Fail if the system is not running the latest kernel
      ansible.builtin.fail:
        msg: "The system is not running the latest kernel version after reboot. Running kernel: {{ running_kernel.stdout }}."
      when: running_kernel.stdout not in installed_kernel_version.stdout
