---
- name: Test apt-cache command output
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Run apt-cache madison for linux-image-generic
      command: apt-cache madison linux-image-generic
      register: apt_cache_output

    - name: Display the output of the apt-cache command
      debug:
        var: apt_cache_output
