---
- name: Ensure the system is running the latest Ubuntu kernel
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Update the package list
      ansible.builtin.apt:
        update_cache: yes

    - name: Get the latest available kernel version from linux-image-generic
      shell: apt-cache madison linux-image-generic | awk '{print $3}' | sort -V | tail -n 1
      register: latest_kernel_version
      changed_when: false

    - name: Debug the latest available kernel version
      debug:
        msg: "Latest available kernel version: {{ latest_kernel_version.stdout.strip() }}"

    - name: Convert the kernel version to the correct package format
      set_fact:
        kernel_package_version: "{{ latest_kernel_version.stdout.strip() | regex_replace('\\.', '-') | regex_replace('-(\\d+)-', '-\\1-') }}"

    - name: Debug the converted kernel package version
      debug:
        msg: "Kernel package version: {{ kernel_package_version }}"

    - name: Get the currently running kernel version
      command: uname -r
      register: current_kernel_version
      changed_when: false

    - name: Debug the current running kernel version
      debug:
        msg: "Current running kernel version: {{ current_kernel_version.stdout.strip() }}"

    - name: Install the specific latest available kernel version
      apt:
        name:
          - "linux-image-{{ kernel_package_version }}-generic"
          - "linux-headers-{{ kernel_package_version }}-generic"
          - "linux-modules-{{ kernel_package_version }}-generic"
        state: present
      when: current_kernel_version.stdout.strip() not in kernel_package_version
      register: kernel_installed

    - name: Check if a reboot is required
      shell: |
        if [ -f /var/run/reboot-required ]; then echo "reboot_required"; fi
      register: reboot_required
      changed_when: reboot_required.stdout != ""
      check_mode: no

    - name: Reboot the server if the kernel was updated
      ansible.builtin.reboot:
      when: kernel_installed.changed and reboot_required.stdout == "reboot_required"

    - name: Verify the running kernel after reboot
      command: uname -r
      register: running_kernel
      changed_when: false

    - name: Display the running kernel after reboot
      debug:
        msg: "The system is now running kernel version {{ running_kernel.stdout.strip() }}."

    - name: Fail if the system is not running the latest kernel
      ansible.builtin.fail:
        msg: "The system is not running the latest kernel version. Expected: {{ kernel_package_version }}, but running: {{ running_kernel.stdout.strip() }}."
      when: running_kernel.stdout.strip() != kernel_package_version
