---
- name: Ensure the system is running the latest Ubuntu kernel
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Update the package list
      ansible.builtin.apt:
        update_cache: yes

    - name: Get the latest available kernel package names
      shell: |
        apt-cache madison linux-image-generic | awk '{print $3}' | sort -V | tail -n 1
      register: latest_kernel_version
      changed_when: false

    - name: Get the actual package names from the version string
      shell: |
        apt-cache madison linux-image-{{ latest_kernel_version.stdout.strip() }} | awk '{print $1}'
      register: package_names
      changed_when: false

    - name: Debug the package names
      debug:
        msg: "Kernel package names: {{ package_names.stdout_lines }}"

    - name: Get the currently running kernel version
      command: uname -r
      register: current_kernel_version
      changed_when: false

    - name: Debug the current running kernel version
      debug:
        msg: "Current running kernel version: {{ current_kernel_version.stdout.strip() }}"

    - name: Install the latest available kernel
      apt:
        name: "{{ item }}"
        state: present
      loop: "{{ package_names.stdout_lines }}"
      when: current_kernel_version.stdout.strip() not in latest_kernel_version.stdout.strip()
      register: kernel_installed

    - name: Check if a reboot is required
      shell: |
        if [ -f /var/run/reboot-required ]; then echo "reboot_required"; fi
      register: reboot_required
      changed_when: reboot_required.stdout != ""
      check_mode: no

    - name: Reboot the server if the kernel was updated
      ansible.builtin.reboot:
      when: kernel_installed.changed and reboot_required.stdout == "reboot_required"

    - name: Verify the running kernel after reboot
      command: uname -r
      register: running_kernel
      changed_when: false

    - name: Display the running kernel after reboot
      debug:
        msg: "The system is now running kernel version {{ running_kernel.stdout.strip() }}."

    - name: Fail if the system is not running the latest kernel
      ansible.builtin.fail:
        msg: "The system is not running the latest kernel version. Expected: {{ latest_kernel_version.stdout.strip() }}, but running: {{ running_kernel.stdout.strip() }}."
      when: running_kernel.stdout.strip() != latest_kernel_version.stdout.strip()
