---
- name: Ensure the system is running the latest Ubuntu kernel
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Update the package list
      ansible.builtin.apt:
        update_cache: yes

    - name: Get the latest available kernel version from linux-image-generic
      shell: apt-cache madison linux-image-generic | awk '{print $3}' | sort -V | tail -n 1
      register: latest_kernel_version
      failed_when: latest_kernel_version.stdout is undefined

    - name: Get the currently running kernel version
      command: uname -r
      register: current_kernel_version
      failed_when: current_kernel_version.stdout is undefined

    - name: Display kernel versions
      debug:
        msg: "Current kernel: {{ current_kernel_version.stdout.strip() }}, Latest available kernel: {{ latest_kernel_version.stdout.strip() }}"

    - name: Install the latest available kernel if not already installed
      apt:
        name: "linux-image-{{ latest_kernel_version.stdout.strip() }}"
        state: present
      when: current_kernel_version.stdout.strip() not in latest_kernel_version.stdout.strip()
      register: kernel_installed

    - name: Check if a reboot is required
      shell: |
        if [ -f /var/run/reboot-required ]; then echo "reboot_required"; fi
      register: reboot_required
      changed_when: reboot_required.stdout != ""
      check_mode: no

    - name: Reboot the server if the kernel was updated
      ansible.builtin.reboot:
      when: kernel_installed.changed and reboot_required.stdout == "reboot_required"

    - name: Verify the running kernel after reboot
      command: uname -r
      register: running_kernel
      failed_when: running_kernel.stdout is undefined

    - name: Display the running kernel
      debug:
        msg: "The system is now running kernel version {{ running_kernel.stdout.strip() }}."

    - name: Fail if the system is not running the latest kernel
      ansible.builtin.fail:
        msg: "The system is not running the latest kernel version. Expected: {{ latest_kernel_version.stdout.strip() }}, but running: {{ running_kernel.stdout.strip() }}."
      when: running_kernel.stdout.strip() != latest_kernel_version.stdout.strip()
