---
- name: Patch and Maintain Ubuntu Linux VMs (Enhanced)
  hosts: all
  become: yes
  gather_facts: yes  
  vars:
    allow_reboot: true  # Set to true to allow reboot when needed

  tasks:

    # Step 1: Update the APT cache
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      tags: [update]

    # Step 2: Upgrade installed packages
    - name: Upgrade all installed packages to the latest version
      apt:
        upgrade: dist
        autoclean: yes
        autoremove: yes
      tags: [upgrade]

    # Step 3: Perform a distribution upgrade
    - name: Perform a distribution upgrade
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
      tags: [upgrade]

    # Step 4: Remove unused packages
    - name: Remove unused packages
      apt:
        name: "{{ item }}"
        state: absent
      loop: "{{ ansible_facts.packages | selectattr('state', 'equalto', 'removed') | map(attribute='package') | list }}"
      when: ansible_facts.packages is defined
      tags: [clean]

    # Step 5: Clean up APT cache
    - name: Clean up apt cache
      apt:
        autoclean: yes
      tags: [clean]

    # Step 6: Get current kernel version
    - name: Get current kernel version
      shell: uname -r | cut -d'-' -f1,2
      register: kernel_version
      changed_when: false
      tags: [kernel]

    - name: Show current kernel version
      debug:
        msg: "Current kernel version is: {{ kernel_version.stdout }}"
      tags: [kernel]

    # Step 7: Get installed kernel version (clean output)
    - name: Get installed kernel version (removing extra build metadata)
      shell: "apt-cache policy linux-image-azure | grep 'Installed:' | awk '{print $2}' | sed 's/\\.[0-9]\\+~.*$//'"
      register: installed_kernel
      changed_when: false
      tags: [kernel]

    # Step 8: Determine if a new kernel is available
    - name: Determine next kernel version
      set_fact:
        kernel_message: >-
          {% if kernel_version.stdout == installed_kernel.stdout %}
          "Current version is {{ kernel_version.stdout }}. This is the latest kernel."
          {% else %}
          "Current version is {{ kernel_version.stdout }}, but after reboot {{ installed_kernel.stdout }} will be applied."
          {% endif %}

    - name: Show next kernel version that will be applied after reboot
      debug:
        msg: "{{ kernel_message }}"
      tags: [kernel]

    # Step 9: Ensure reboot_required is always defined
    - name: Initialize reboot_required variable
      set_fact:
        reboot_required: false

    # Step 10: Check if reboot is required
    - name: Determine if reboot is required
      set_fact:
        reboot_required: "{{ installed_kernel.stdout is defined and installed_kernel.stdout != '' and kernel_version.stdout != installed_kernel.stdout }}"

    # Step 11: Show reboot required status
    - name: Show reboot required status
      debug:
        msg: >-
          {% if reboot_required %}
          "Reboot is required: True. If 'true', please set 'allow_reboot: true' to apply the new kernel."
          {% else %}
          "Reboot is not required. This is the latest kernel."
          {% endif %}
      tags: [reboot]

    # Step 12: Stop execution if no reboot is required
    - name: Stop playbook execution if no reboot is required
      meta: end_play
      when: not reboot_required
      tags: [reboot]

    # Step 13: Stop execution if reboot is required but not allowed
    - name: Stop playbook execution if reboot is required but not allowed
      meta: end_play
      when: reboot_required and not allow_reboot
      tags: [reboot]

    # Step 14: Reboot the server if allowed and required
    - name: Reboot the server if allowed and required
      reboot:
        post_reboot_delay: 30
      when: allow_reboot | bool and reboot_required | bool
      tags: [reboot]

    # Step 15: Verify the kernel version after reboot
    - name: Gather facts after reboot
      setup:
      when: allow_reboot | bool and reboot_required | bool

    - name: Verify current kernel version after reboot
      shell: uname -r | cut -d'-' -f1,2
      register: new_kernel_version
      changed_when: false
      tags: [verify]

    - name: Show new kernel version after reboot
      debug:
        msg: "Kernel after reboot: {{ new_kernel_version.stdout }}"
      tags: [verify]

    - name: Verify if reboot successfully applied the new kernel
      debug:
        msg: "Reboot was successful: Kernel updated to {{ new_kernel_version.stdout }}."
      when: new_kernel_version.stdout == installed_kernel.stdout
      tags: [verify]
