---
- name: Check Uptime
  hosts: all
  gather_facts: no

  tasks:
    - name: Run uptime command
      ansible.builtin.command: uptime
      register: uptime_output

    - name: Display uptime
      ansible.builtin.debug:
        var: uptime_output.stdout_lines
