---
- name: Check Memory Usage
  hosts: all
  gather_facts: no

  tasks:
    - name: Run free command to check memory
      ansible.builtin.command: free -m
      register: memory_output

    - name: Display memory usage
      ansible.builtin.debug:
        var: memory_output.stdout_lines
