---
- name: Test Kernel Installation Process
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Notify: Starting the process
      ansible.builtin.debug:
        msg: "Starting the process to install Kernel 5.15.0-116.126"
