---
- name: Install and switch to Kernel 5.15.0-116.126
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Install the specific kernel version 5.15.0-116.126
      ansible.builtin.apt:
        name: 
          - linux-image-5.15.0-116-generic
          - linux-headers-5.15.0-116-generic
          - linux-modules-5.15.0-116-generic
        state: present
      register: install_kernel_result
      notify:
        - Kernel installation completed

    - name: Update GRUB to use the new kernel
      ansible.builtin.command:
        cmd: update-grub
      register: update_grub_result
      notify:
        - GRUB update completed

    - name: Reboot the server to apply the new kernel
      ansible.builtin.reboot:
        reboot_timeout: 600
      notify:
        - Server rebooted

  handlers:
    - name: Kernel installation completed
      ansible.builtin.debug:
        msg: "Kernel 5.15.0-116.126 installation completed."

    - name: GRUB update completed
      ansible.builtin.debug:
        msg: "GRUB update completed."

    - name: Server rebooted
      ansible.builtin.debug:
        msg: "Server has been rebooted to apply the new kernel."
