---
- name: Install and switch to Kernel 5.15.0-116.126
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Install the specific kernel version 5.15.0-116.126
      ansible.builtin.apt:
        name: 
          - "linux-image-5.15.0-116-generic"
          - "linux-headers-5.15.0-116-generic"
          - "linux-modules-5.15.0-116-generic"
        state: present

    - name: Update GRUB to use the new kernel
      ansible.builtin.command: update-grub

    - name: Reboot the server to apply the new kernel
      ansible.builtin.reboot:
        reboot_timeout: 600
