# ---
# - name: Check OS Type and Version on localhost
#   hosts: localhost
#   connection: local
#   tasks:
#     - name: Gather system facts
#       setup:

#     - name: Display the OS name and version
#       debug:
#         msg:
#           - "OS Name: {{ ansible_facts['os_family'] }}"
#           - "OS Version: {{ ansible_facts['distribution_version'] }}"
#           - "OS Type: {{ ansible_facts['distribution'] }}"
---
- name: Check Python and Ansible versions and installation directories in ansible-venv
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Check Python version in ansible-venv
      command: /semaphore/ansible-venv/bin/python3 --version
      register: python_version
      ignore_errors: true

    - name: Check Ansible version in ansible-venv
      command: /semaphore/ansible-venv/bin/ansible --version
      register: ansible_version
      ignore_errors: true

    - name: Find Python installation directories in ansible-venv
      command: which /semaphore/ansible-venv/bin/python3
      register: python_directory
      ignore_errors: true

    - name: Find Ansible installation directories in ansible-venv
      command: which /semaphore/ansible-venv/bin/ansible
      register: ansible_directory
      ignore_errors: true

    - name: Ensure Ansible uses the virtualenv python interpreter
      lineinfile:
        path: /etc/ansible/ansible.cfg
        regexp: '^#?ansible_python_interpreter'
        line: "ansible_python_interpreter = /semaphore/ansible-venv/bin/python3"
        create: yes

    - name: Output results
      debug:
        msg:
          - "Python Version: {{ python_version.stdout if python_version.stdout is defined else 'not installed' }}"
          - "Ansible Version: {{ ansible_version.stdout if ansible_version.stdout is defined else 'Ansible not found in ansible-venv' }}"
          - "Python Installation Directory: {{ python_directory.stdout if python_directory.stdout is defined else 'Python not found in ansible-venv' }}"
          - "Ansible Installation Directory: {{ ansible_directory.stdout if ansible_directory.stdout is defined else 'Ansible not found in ansible-venv' }}"
