---
- name: Check Kernel Version
  hosts: all
  gather_facts: no

  tasks:
    - name: Get kernel version
      ansible.builtin.command: uname -r
      register: kernel_version_output

    - name: Display kernel version
      ansible.builtin.debug:
        var: kernel_version_output.stdout
