# ---
# - name: Check OS Type and Version on localhost
#   hosts: localhost
#   connection: local
#   tasks:
#     - name: Gather system facts
#       setup:

#     - name: Display the OS name and version
#       debug:
#         msg:
#           - "OS Name: {{ ansible_facts['os_family'] }}"
#           - "OS Version: {{ ansible_facts['distribution_version'] }}"
#           - "OS Type: {{ ansible_facts['distribution'] }}"
---
- name: Check Python and Ansible versions and installation directories in ansible-venv
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Run inline bash script to check Python and Ansible versions
      command: >
        bash -c "
          source /semaphore/ansible-venv/bin/activate &&
          echo 'Python Version:' &&
          /semaphore/ansible-venv/bin/python3 --version &&
          echo 'Ansible Version:' &&
          /semaphore/ansible-venv/bin/ansible --version &&
          echo 'Python Installation Directory:' &&
          which /semaphore/ansible-venv/bin/python3 &&
          echo 'Ansible Installation Directory:' &&
          which /semaphore/ansible-venv/bin/ansible"
      register: result
      ignore_errors: true

    - name: Output the result of inline script
      debug:
        msg: "{{ result.stdout }}"
