---
- name: Check OS Type and Version on localhost
  hosts: localhost
  connection: local
  tasks:
    - name: Gather system facts
      setup:

    - name: Display the OS name and version
      debug:
        msg:
          - "OS Name: {{ ansible_facts['os_family'] }}"
          - "OS Version: {{ ansible_facts['distribution_version'] }}"
          - "OS Type: {{ ansible_facts['distribution'] }}"
