---
- name: Run tasks without requiring sudo
  hosts: all
  tasks:
    - name: Print the current working directory
      command: pwd

    - name: List files in the home directory
      command: ls -la ~

    - name: Display a message
      debug:
        msg: "This task does not require sudo!"
