---
- name: Upgrade Ubuntu from 22.04 LTS to 24.04 LTS
  hosts: all
  become: yes
  tasks:
    - name: Update all packages to the latest version
      apt:
        update_cache: yes
        upgrade: dist
        force_apt_get: yes

    - name: Install the Update Manager Core
      apt:
        name: update-manager-core
        state: present

    - name: Do-release-upgrade to upgrade to Ubuntu 24.04 LTS
      command: do-release-upgrade -d
      args:
        creates: "/var/run/reboot-required"
      register: upgrade

    - name: Check if reboot is needed
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot the machine if required
      reboot:
      when: reboot_required.stat.exists

    - name: Wait for system to come back after reboot
      wait_for_connection:
        delay: 60
        timeout: 300
