---
- hosts: all
  become: yes
  gather_facts: no
  vars:
    script_url: "https://raw.githubusercontent.com/baydullod/ansbile/main/upgrade_kernel_latest.sh"
    script_path: "/tmp/upgrade_kernel_latest.sh"

  tasks:
    - name: Ensure curl is installed
      apt:
        name: curl
        state: present

    - name: Download the kernel upgrade script
      get_url:
        url: "{{ script_url }}"
        dest: "{{ script_path }}"
        mode: '0755'

    - name: Execute the kernel upgrade script
      script: "{{ script_path }}"
      args:
        executable: /bin/bash

    - name: Reboot the server if needed
      reboot:
        msg: "Rebooting to apply the new kernel"
        pre_reboot_delay: 10
